import { useEffect, useMemo, useRef, useState } from 'react';
import { db, getSettings } from './db';
import { appendImportedWords, createSession, dedupeImport, ensureSpellingQueue, localDate, recordAnswer, remainingInRound } from './logic';
import { mappedRows, parseFile } from './importer';
import { dictationKeyAction } from './keyboard';
import type { AppSettings, DailySession, Word } from './types';
const blank: AppSettings={id:'settings',rate:.85,volume:1,theme:'light'};
function speak(text:string,s:AppSettings){ speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=s.rate;u.volume=s.volume;u.voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('en-US'))||speechSynthesis.getVoices().find(v=>v.lang.startsWith('en'))||null;speechSynthesis.speak(u); }
const Btn=({children,...p}:React.ButtonHTMLAttributes<HTMLButtonElement>)=><button type="button" {...p}>{children}</button>;
export default function App(){
 const [page,setPage]=useState<'today'|'history'|'words'|'data'>('today'),[words,setWords]=useState<Word[]>([]),[session,setSession]=useState<DailySession|null>(null),[settings,setSettings]=useState<AppSettings>(blank),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState<'ok'|'bad'|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[preview,setPreview]=useState<string[][]|null>(null),[importFile,setImportFile]=useState<File|null>(null),[sheets,setSheets]=useState<string[]>([]),[selectedSheet,setSelectedSheet]=useState(''),[columns,setColumns]=useState({word:0,meaning:1,phonetic:2}),[date,setDate]=useState(localDate()),[history,setHistory]=useState<DailySession|null>(null);
 const input=useRef<HTMLInputElement>(null),pending=useRef<DailySession|null>(null);
 const load=async()=>{const ws=await db.words.toArray();setWords(ws);let s=await db.sessions.get(localDate());if(!s){s=createSession(localDate(),ws);await db.sessions.put(s)}setSession(s);setSettings(await getSettings())};
 useEffect(()=>{void load()},[]);useEffect(()=>{document.documentElement.dataset.theme=settings.theme},[settings]);
 const saveSession=async(s:DailySession)=>{await db.sessions.put(s);setSession(s)};
 const current=session?words.find(w=>w.id===session.queue[session.currentIndex]):undefined;
 useEffect(()=>{if(session?.phase==='spell'&&current&&!feedback){speak(current.text,settings);setTimeout(()=>input.current?.focus(),0)}},[session?.phase,session?.currentIndex,current?.id,feedback,settings]);
 async function startSpelling(){if(!session)return;const fixed=ensureSpellingQueue(session);await saveSession({...fixed,phase:'spell'});}
 async function repairQueue(){if(session)await saveSession(ensureSpellingQueue(session));}
 async function submit(){if(!current||!session||feedback)return;const correct=answer.trim().toLowerCase()===current.text.trim().toLowerCase(),next=recordAnswer(session,current.id!,answer,current.text);await db.attempts.add({date:session.date,wordId:current.id!,round:session.round,answer,correct,createdAt:new Date().toISOString()});await db.words.update(current.id!,next.masteredIds.includes(current.id!)&&!session.masteredIds.includes(current.id!)?{status:'mastered',streak:3,correctCount:current.correctCount+1}:{streak:next.progresses[current.id!].streak,correctCount:current.correctCount+(correct?1:0),wrongCount:current.wrongCount+(correct?0:1)});pending.current=next;setFeedback(correct?'ok':'bad');speak(current.text,settings);if(correct)setTimeout(()=>void nextQuestion(),600);}
 async function nextQuestion(){if(!pending.current)return;await saveSession(pending.current);pending.current=null;setAnswer('');setFeedback(null);}
 function onDictationKey(e:React.KeyboardEvent<HTMLInputElement>){const action=dictationKeyAction(e.key,e.code,feedback);if(action==='none')return;e.preventDefault();if(action==='replay'&&current){speak(current.text,settings);input.current?.focus()}else if(action==='submit')void submit();else if(action==='next')void nextQuestion();}
 async function importRows(){if(!preview)return;const out=dedupeImport(mappedRows(preview,columns.word,columns.meaning,columns.phonetic),words.map(w=>w.text));const ids=await db.words.bulkAdd(out.added.map(x=>({text:x.word,meaning:x.meaning||'',phonetic:x.phonetic||'',status:'learning',streak:0,correctCount:0,wrongCount:0,createdAt:new Date().toISOString()})),{allKeys:true});if(session)await saveSession(appendImportedWords(session,ids.map(Number)));setPreview(null);setImportFile(null);setSheets([]);await load();alert(`已新增 ${out.added.length} 个；重复 ${out.duplicate} 个；无效 ${out.invalid} 个。`)}
 async function choose(file:File){try{setImportFile(file);const p=await parseFile(file);setPreview(p.rows);setSheets(p.sheets);setSelectedSheet(p.sheets[0]||'')}catch{alert('解析失败，请检查文件格式。')}}
 const visible=useMemo(()=>words.filter(w=>(!query||w.text.toLowerCase().includes(query.toLowerCase())||w.meaning.includes(query))&&(filter==='all'||w.status===filter||(filter==='qualified'&&session?.progresses[w.id!]?.qualified))),[words,query,filter,session]);
 const qualified=session?Object.values(session.progresses).filter(p=>p.qualified).length:0;
 return <main><header><div><b>每日单词循环</b><small>离线、可持续的听写练习</small></div><nav>{[['today','今日学习'],['history','历史记录'],['words','词库管理'],['data','数据与设置']].map(([key,label])=><Btn className={page===key?'active':''} onClick={()=>setPage(key as typeof page)} key={key}>{label}</Btn>)}</nav></header>
 {page==='today'&&<section>{!session?<p>正在加载…</p>:<><div className="title"><div><h1>{session.date} · 今日学习</h1><p>共 {session.wordIds.length} 个单词，已达标 {qualified} 个 · 第 {session.round} 轮</p></div><span className="badge">{session.phase==='browse'?'阶段一：浏览记忆':'阶段二：听音拼写'}</span></div><progress value={qualified} max={Math.max(session.wordIds.length,1)}/>{session.wordIds.length===0?<Empty text="词库为空，先到“数据与设置”导入单词吧。"/>:session.completed?<Empty text="此书单词背完，你太棒了！"/>:session.phase==='browse'?<div className="card"><h2>先浏览单词表</h2><div className="wordgrid">{session.wordIds.map(id=>{const w=words.find(x=>x.id===id);return w&&<Btn className="word" key={id} onClick={()=>speak(w.text,settings)}><b>{w.text}</b><span>{w.phonetic}</span><small>{w.meaning||'未填写释义'}</small></Btn>})}</div><Btn className="primary" onClick={()=>void startSpelling()}>开始听音拼写</Btn></div>:!current?<div className="card error"><h2>本轮队列需要修复</h2><p>检测到仍有待学习单词，但当前没有可显示的单词。不会丢失已有进度。</p><Btn className="primary" onClick={()=>void repairQueue()}>修复本轮队列</Btn></div>:<div className="card practice"><p>本轮剩余 {remainingInRound(session)} 个 · 正确率 {session.correct+session.wrong?Math.round(session.correct/(session.correct+session.wrong)*100):0}%</p><Btn className="sound" onClick={()=>{speak(current.text,settings);input.current?.focus()}}>播放发音（空格）</Btn><h2>请听音后拼写</h2><input ref={input} autoFocus value={answer} disabled={!!feedback} onChange={e=>setAnswer(e.target.value)} onKeyDown={onDictationKey} placeholder="输入英文单词"/>{feedback&&<div className={feedback==='ok'?'success':'error'}>{feedback==='ok'?'✓ 拼写正确':`✕ 正确答案：${current.text}`}</div>}<Btn className="primary" disabled={!!feedback} onClick={()=>void submit()}>提交答案（Enter）</Btn>{feedback==='bad'&&<Btn onClick={()=>void nextQuestion()}>确认，下一题</Btn>}</div>}</>}</section>}
 {page==='history'&&<section><h1>历史记录</h1><input type="date" max={localDate()} value={date} onChange={async e=>{setDate(e.target.value);setHistory(await db.sessions.get(e.target.value)||null)}}/><Btn onClick={async()=>setHistory(await db.sessions.get(date)||null)}>查看</Btn>{history?<div className="card"><h2>{date}</h2><p>学习单词：{history.wordIds.length} · 完成：{Object.values(history.progresses).filter(x=>x.qualified).length} · 正确：{history.correct} · 错误：{history.wrong}</p><p>拼写轮数：{history.round} · {history.completed?'已完成':'未完成'} · 当天新掌握：{history.masteredIds.length} 个</p></div>:<Empty text="该日期没有学习记录。"/>}</section>}
 {page==='words'&&<section><h1>词库管理</h1><div className="toolbar"><input placeholder="搜索单词或释义" value={query} onChange={e=>setQuery(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部状态</option><option value="learning">学习中</option><option value="qualified">今日已达标</option><option value="mastered">已掌握</option><option value="paused">已暂停</option></select></div><div className="table">{visible.map(w=><article key={w.id}><div><b onClick={()=>speak(w.text,settings)}>{w.text} 🔊</b><span>{w.phonetic}　{w.meaning}</span><small>连续达标 {w.streak} 轮 · 正确 {w.correctCount} · 错误 {w.wrongCount} · {w.status}</small></div><Btn onClick={async()=>{const meaning=prompt('释义',w.meaning),phonetic=prompt('音标',w.phonetic);if(meaning!==null&&phonetic!==null){await db.words.update(w.id!,{meaning,phonetic});void load()}}}>编辑</Btn><Btn onClick={async()=>{await db.words.update(w.id!,{status:w.status==='paused'?'learning':'paused'});void load()}}>{w.status==='paused'?'恢复':'暂停'}</Btn><Btn className="danger" onClick={async()=>{if(confirm('删除此单词？')){await db.words.delete(w.id!);void load()}}}>删除</Btn></article>)}</div>{!visible.length&&<Empty text="没有符合条件的单词。"/>}</section>}
 {page==='data'&&<section><h1>数据与设置</h1><div className="card"><h2>导入词库</h2><input type="file" accept=".txt,.csv,.xlsx" onChange={e=>e.target.files?.[0]&&void choose(e.target.files[0])}/><a href="/sample-vocabulary.csv" download>下载词库模板</a>{preview&&<div><p>预览：{preview.length-1} 行（{importFile?.name}）</p>{sheets.length>1&&<label>工作表 <select value={selectedSheet} onChange={async e=>{const value=e.target.value;setSelectedSheet(value);if(importFile)setPreview((await parseFile(importFile,value)).rows)}}>{sheets.map(name=><option key={name}>{name}</option>)}</select></label>}<div className="mapping">{(['word','meaning','phonetic'] as const).map(field=><label key={field}>{field} 列 <select value={columns[field]} onChange={e=>setColumns({...columns,[field]:Number(e.target.value)})}>{(preview[0]||[]).map((name,index)=><option key={index} value={index}>{String.fromCharCode(65+index)}：{name||'空列'}</option>)}</select></label>)}</div><pre>{preview.slice(0,5).map(x=>x.join(' | ')).join('\n')}</pre><Btn className="primary" onClick={()=>void importRows()}>确认列映射并导入</Btn><Btn onClick={()=>setPreview(null)}>取消</Btn></div>}</div><div className="card"><h2>语音与外观</h2><label>语速 <input type="range" min="0.5" max="1.5" step="0.1" value={settings.rate} onChange={e=>{const n={...settings,rate:+e.target.value};setSettings(n);void db.settings.put(n)}}/>{settings.rate}</label><label>音量 <input type="range" min="0" max="1" step="0.1" value={settings.volume} onChange={e=>{const n={...settings,volume:+e.target.value};setSettings(n);void db.settings.put(n)}}/></label><Btn onClick={()=>{const n:AppSettings={...settings,theme:settings.theme==='light'?'dark':'light'};setSettings(n);void db.settings.put(n)}}>切换{settings.theme==='light'?'深色':'浅色'}模式</Btn></div><div className="card"><h2>备份与恢复</h2><Btn onClick={async()=>{const data={words:await db.words.toArray(),sessions:await db.sessions.toArray(),attempts:await db.attempts.toArray(),settings:await db.settings.toArray()};const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));link.download='每日单词循环备份.json';link.click()}}>导出完整备份</Btn><input type="file" accept=".json" onChange={async e=>{const file=e.target.files?.[0];if(file&&confirm('恢复会覆盖现有全部数据，确认吗？')){try{const backup=JSON.parse(await file.text());await db.transaction('rw',db.words,db.sessions,db.attempts,db.settings,async()=>{await db.words.clear();await db.sessions.clear();await db.attempts.clear();await db.settings.clear();await db.words.bulkAdd(backup.words||[]);await db.sessions.bulkPut(backup.sessions||[]);await db.attempts.bulkAdd(backup.attempts||[]);await db.settings.bulkPut(backup.settings||[])});void load()}catch{alert('备份文件无效')}}}}/><Btn className="danger" onClick={async()=>{if(confirm('确定清除全部数据？此操作无法撤销。')&&confirm('请再次确认：真的要删除所有词库和历史吗？')){await db.delete();location.reload()}}}>清除全部数据</Btn></div></section>}</main>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
