import type { ImportRow } from './types';
export type ParsedFile = { sheets: string[]; rows: string[][] };
type WorkbookSheet = { sheet: string; data: unknown[][] };
function csvRows(text:string):string[][] { const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c==='"'&&quoted&&next==='"'){field+=c;i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&next==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field=''}else field+=c}row.push(field);if(row.some(v=>v.trim()))rows.push(row);return rows; }
/** Gets the worksheet names from read-excel-file's workbook result. */
export function getSheets(workbook:WorkbookSheet[]) { return workbook.map(entry => entry.sheet); }
/** Selects a named sheet returned by read-excel-file's workbook metadata/data call. */
export function selectXlsxSheet(workbook:WorkbookSheet[], sheet?:string):ParsedFile { const sheets=getSheets(workbook);const selected=workbook.find(entry=>entry.sheet===(sheet??sheets[0]))?.data??[];return {sheets,rows:selected.map(row=>row.map(cell=>cell==null?'':String(cell)))}; }
export async function parseFile(file:File,sheet?:string):Promise<ParsedFile>{const name=file.name.toLowerCase();if(name.endsWith('.txt'))return{sheets:['文本'],rows:(await file.text()).split(/\r?\n/).map(line=>line.split('\t'))};if(name.endsWith('.csv'))return{sheets:['CSV'],rows:csvRows(await file.text())};const {default:readXlsxFile}=await import('read-excel-file/browser');/* The library returns the workbook's sheet metadata and data in one call. */return selectXlsxSheet(await readXlsxFile(file) as WorkbookSheet[],sheet);}
export function mappedRows(rows:string[][],wordCol:number,meaningCol?:number,phoneticCol?:number,header=true):ImportRow[]{return rows.slice(header?1:0).map(row=>({word:String(row[wordCol]??''),meaning:meaningCol===undefined?'':String(row[meaningCol]??''),phonetic:phoneticCol===undefined?'':String(row[phoneticCol]??'')}));}
